"""added_cascade_for_URL

Revision ID: d627ffc22b8d
Revises: 43e6a0fef559
Create Date: 2026-03-21 23:08:22.967989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd627ffc22b8d'
down_revision: Union[str, None] = '43e6a0fef559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('clickevent_url_id_fkey'), 'clickevent', type_='foreignkey')
    op.create_foreign_key(None, 'clickevent', 'url', ['url_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clickevent', type_='foreignkey')
    op.create_foreign_key(op.f('clickevent_url_id_fkey'), 'clickevent', 'url', ['url_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
